### ISSUE TITLE
AttributeError: 'SmartScraperGraph' object has no attribute 'model_token'

### ISSUE THREAD

**Issue by waqaskhan137** [VinciGit00/Scrapegraph-ai#103]
**Describe the bug**
I just followed the instruction and ran the example and getting the following error 

I have verified ollama is running and I can use the models using ollama-webui

I am using following models and those are downloaded and working in webui

ollama/gemma:2b
ollama/nomic-embed-text"

![image](https://github.com/VinciGit00/Scrapegraph-ai/assets/4752256/517215c4-1040-4aa2-be4f-210042b16991)

```
Traceback (most recent call last):
  File "/home/leo/dev/projs/scrapegraph/main.py", line 16, in <module>
    smart_scraper_graph = SmartScraperGraph(
                          ^^^^^^^^^^^^^^^^^^
  File "/home/leo/dev/projs/scrapegraph/.venv/lib/python3.11/site-packages/scrapegraphai/graphs/smart_scraper_graph.py", line 24, in __init__
    super().__init__(prompt, config, source)
  File "/home/leo/dev/projs/scrapegraph/.venv/lib/python3.11/site-packages/scrapegraphai/graphs/abstract_graph.py", line 25, in __init__
    self.graph = self._create_graph()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/dev/projs/scrapegraph/.venv/lib/python3.11/site-packages/scrapegraphai/graphs/smart_scraper_graph.py", line 39, in _create_graph
    node_config={"chunk_size": self.model_token}
                               ^^^^^^^^^^^^^^^^
AttributeError: 'SmartScraperGraph' object has no attribute 'model_token'

Process finished with exit code 1

```

**To Reproduce**
1. Run Ollama using docker 
2. copy paste the example
3. install scrapegraphai 

**Expected behavior**
It should work seamlessly
 
**Screenshots**
![image](https://github.com/VinciGit00/Scrapegraph-ai/assets/4752256/2c709f95-1018-4f25-a644-98f946e551d2)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10

**Comment by VinciGit00** [comment]
Hi, we did on the branch, just wait till the deployment is done 
The configuration is the following:
`""" 
Basic example of scraping pipeline using SmartScraper
"""
from scrapegraphai.graphs import SmartScraperGraph
from scrapegraphai.utils import prettify_exec_info
# ************************************************
# Define the configuration for the graph
# ************************************************

graph_config = {
    "llm": {
        "model": "ollama/gemma",
        "temperature": 0,
        "format": "json",  # Ollama needs the format to be specified explicitly
        # "model_tokens": 2000, # set context length arbitrarily,
        "base_url": "http://localhost:11434",  # set ollama URL arbitrarily
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "temperature": 0,
        "base_url": "http://localhost:11434",  # set ollama URL arbitrarily
    }
}

# ************************************************
# Create the SmartScraperGraph instance and run it
# ************************************************

smart_scraper_graph = SmartScraperGraph(
    prompt="List me all the news with their description.",
    # also accepts a string with the already downloaded HTML code
    source="https://perinim.github.io/projects",
    config=graph_config
)

result = smart_scraper_graph.run()
print(result)

# ************************************************
# Get graph execution info
# ************************************************

graph_exec_info = smart_scraper_graph.get_execution_info()
print(prettify_exec_info(graph_exec_info))`, When we make the next deploy you can use it, just wait

<img width="1459" alt="Screenshot 2024-04-29 alle 11 05 35" src="https://github.com/VinciGit00/Scrapegraph-ai/assets/88108002/22324503-6b28-44de-b522-b20cf8cfb416">
