### ISSUE TITLE
Add verbosity flag to remove print statements

### ISSUE THREAD

**Issue by 0xj7r** [VinciGit00/Scrapegraph-ai#109]
**Is your feature request related to a problem? Please describe.**

The print statements make the outputs too verbose - it would be useful to optionally disable them using a flag

**Describe the solution you'd like**

Add an optional flag in the node classes to remove print statements

**Comment by VinciGit00** [comment]
what would you like to remove? every node print (where is the node in the exact moment) or just the print inside the node?

**Comment by PeriniM** [comment]
Implemented it in 6b22a9d.
Now you can add the `verbose` flag in the graph_config
