### ISSUE TITLE
How to use Azure portal PAT to scrap the data

### ISSUE THREAD

**Issue by krantikumara** [VinciGit00/Scrapegraph-ai#118]
I use the Azure DevOps portal for managing bug data, which I currently access using a Personal Access Token (PAT) and retrieve data through a Python script via APIs. Is it possible to integrate Scrapegraph-AI for this use case?

**Comment by PeriniM** [comment]
Hei can you explain better what you'd like to achieve?
If you want to analyze the response of the API call you could use the JSONScraperGraph and pass the body as "source".

Tell me if it did the trick :)

**Comment by VinciGit00** [comment]
hi, we added it
