### ISSUE TITLE
The ability to use OpenAI embeddings with Groq

### ISSUE THREAD

**Issue by S4mpl3r** [VinciGit00/Scrapegraph-ai#120]
Hey there! It would be great if we could use OpenAI embeddings (or any other supported API-based embedding models) with Groq (or any other supported llm). With the current way the code is organized, you can only use OpenAI embeddings with OpenAI models. If I want to use Groq as my main llm, I would have to use Ollama, which is ok if you want to run models locally. But I don't want to install models on my local machine, I would prefer to use OpenAI as my embedder service.

One way to add this is to change the way ```self.embedder_model``` is initialized in the ```AbstractGraph``` class. Currently, both ```self.llm_model``` and ```self.embedder_model``` are initialized using one method, ```self._create_llm()```, which kinda makes our options limited. One possible solution is to add another function e.g. ```self._create_embedder()``` and completely separate the logic for initialization of llms and embedder models.

**Comment by VinciGit00** [comment]
Thanks! We will do that

**Comment by VinciGit00** [comment]
hi, we did it in this file example! [link](https://github.com/VinciGit00/Scrapegraph-ai/blob/main/examples/groq/smart_scraper_groq_openai.py)

**Comment by S4mpl3r** [comment]
Well, that wasn't the inteded solution but nice workaround haha

**Comment by VinciGit00** [comment]
ok, make a pull request and we will do it

**Comment by S4mpl3r** [comment]
Alright I'll try to implement my solution and will submit a pull request as soon as I get the chance.

**Comment by VinciGit00** [comment]
Remember to read the contributions rules :)
