### ISSUE TITLE
Azure Example

### ISSUE THREAD

**Issue by kmaurinjones** [VinciGit00/Scrapegraph-ai#123]
Hi there, love the idea of the package! I'm looking to use my Azure instance to run this and I can't seem to find any examples of how to do it in the docs and haven't been able to get something working.

This is the starting point of my Azure-based LLM usage. How can I go from this to using this package with one of the models I have hosted there?

Thanks in advance.

```

from openai import AzureOpenAI
client = AzureOpenAI(
    azure_endpoint=my_endpoint,
    api_key=my_api_key,
    api_version=my_api_version
)

message_text = [{"role":"system","content":"You are an AI assistant that helps people find information."}]

completion = client.chat.completions.create(
    model="model_name",
    messages=message_text,
    ...
)

response_str = completion.choices[0].message.content.strip()
```

**Comment by VinciGit00** [comment]
Pls if it possible send me an email (mvincig11@gmail.com) we would like to help you but we are an open source org and we do not have any api-key. If it is possible we would like to ask you if you can create the temporal key for making the experiments and integrate it. Send me an email

**Comment by VinciGit00** [comment]
hi, we add it :)

**Comment by kmaurinjones** [comment]
Thank you very much! Love the package and I'm grateful for your work :)
