### ISSUE TITLE
Method to pass common params to all the nodes in the graph

### ISSUE THREAD

**Issue by PeriniM** [VinciGit00/Scrapegraph-ai#125]
**Is your feature request related to a problem? Please describe.**
There is no way to pass many parameters all at once to each node in a graph. For example, the `verbose` flag would be nice to have it already in all the nodes.

What I am doing now is defining the params inside the `AbstractGraph` (which is inherited in all the scraping graphs) with something like:

![image](https://github.com/VinciGit00/Scrapegraph-ai/assets/19621159/21e63e33-1295-45de-86b5-594b315cb537)

and then pass it in each node explicitily, for example inside `SmartScraperGraph`:

![image](https://github.com/VinciGit00/Scrapegraph-ai/assets/19621159/0b1df562-844c-4e42-a576-8ef7cffa3568)

You may understand that this method doesn't scale up well.

**Describe the solution you'd like**
I would like a function like this inside `AbstractGraph` that updates all the `node_config` dict for each node:

![image](https://github.com/VinciGit00/Scrapegraph-ai/assets/19621159/2e339b3c-12a7-4c69-b34f-662db09e764d)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by epage480** [comment]
I'm tackling this issue but I have a couple questions on how you'd like it to behave.

If you initialize the graph and have already specified node_config for some nodes in the graph, do you want set_common_params() to overwrite their parameters?

**Comment by PeriniM** [comment]
Hei @epage480, if a parameter is already in the node_config should not be overwritten. If you consider the nodes inside SmartScraperGraph I would remove the verbose param in there and "auto-injecting" it with set_common_params().

Thanks for working on it!

**Comment by shkamboj1** [comment]
@epage480 are you continuing on this ?

**Comment by epage480** [comment]
Yes I'll be submitting a pull request later today

**Comment by DiTo97** [comment]
@PeriniM much needed feature for #147, common config makes a lot of sense for a more efficient proxy rotation, as well.

**Comment by epage480** [comment]
I just submitted a pull request for this issue, let me know what you think!

**Comment by VinciGit00** [comment]
good, thx!
