### ISSUE TITLE
insufficient_quota

### ISSUE THREAD

**Issue by silvacarl2** [VinciGit00/Scrapegraph-ai#131]
**Describe the bug**
keep getting insufficient_quota when testing with google colab.

**To Reproduce**
run the colab example

**Expected behavior**
it is probably rate limiting because it is trying to call openai too fast.

**Screenshots**
run the colab example

**Additional context**
I think if there is a parameter to adjust the rate it is accessing openai API as a parameter to this call smart_scraper_graph.run(), it should work fine.

anotehr approach would be to support some open hosted LLMs, like together.ai llama-3-70b, and it may not have this issue.

**Comment by PeriniM** [comment]
Thanks for the feedback! We will add it, also it is possible to integrate a retry mechanism using [tenacity](https://tenacity.readthedocs.io/en/latest/index.html)

**Comment by silvacarl2** [comment]
ok cool, i will check that out.

also, i need to see ow to get this to work with open LLMs.

**Comment by VinciGit00** [comment]
Let us know man

**Comment by VinciGit00** [comment]
Do u have any news?

**Comment by silvacarl2** [comment]
have not had a chance to focus on this yet but will do.

**Comment by VinciGit00** [comment]
please try the new version

**Comment by silvacarl2** [comment]
still get this error from OpenAI: RateLimitError

**Comment by VinciGit00** [comment]
This is because the website you want to scrape is too big, you have to increase your biking plan on OpenAI
