### ISSUE TITLE
The job post does not contain any body content.

### ISSUE THREAD

**Issue by mdirusso** [VinciGit00/Scrapegraph-ai#132]
**Describe the bug**
I'm trying to scrape the content of a page, asking to summarize the job post. What I get as answer is the following:
"The job post does not contain any body content."

**To Reproduce**
Scrape for example the following [page](https://www.glassdoor.it/job-listing/consulenti-commerciali-studi-medici-med-tech-JV_IC2823223_KO0,35_KE36,44.htm?jl=1009251166481&cs=1_6c21c4d1&s=351&t=FJ&pos=101&src=GD_JOB_AD&guid=0000018f3bec003d9b7a0f6afb8b3553&jobListingId=1009251166481&ea=1&ao=1136043&vt=w&jrtk=5-yul1-0-1hstuo04fhdju807-165a739477bbf907&cb=1714697273616&ctt=1714697324130)

**Expected behavior**
Getting a summary of the page content.

**Comment by VinciGit00** [comment]
Give me here the code example

**Comment by VinciGit00** [comment]
Give me here the code example

**Comment by PeriniM** [comment]
Hei @mdirusso, sometimes if the website is javascript-heavy based, it is recommended to set the `headless` flag to `False` in the graph config. For example:

> graph_config = {
>     "llm": {
>         "api_key": openai_key,
>         "model": "gpt-3.5-turbo",
>     },
>     "verbose":True,
>     "headless":False,
> }
