### ISSUE TITLE
Support Claude3 haiku and others using litellm

### ISSUE THREAD

**Issue by TashaSkyUp** [VinciGit00/Scrapegraph-ai#133]
Claude 3 haiku is cheaper than gpt3.5 and better, adding support for many other models and platforms can easily be completed by using litellm

**Comment by VinciGit00** [comment]
If u want list me the models you would like to have

**Comment by PeriniM** [comment]
@TashaSkyUp it seems like a good addition!
We can support LiteLLM adding a new wrapper inside the `models` module.
[ChatLiteLLM](https://python.langchain.com/docs/integrations/chat/litellm/) and [ChatLiteLLMRouter](https://python.langchain.com/docs/integrations/chat/litellm_router/)

**Comment by PeriniM** [comment]
Closed here 0ab7272, now we can pass directly the llm instance in the graph_config and therefore can be integrated with litellm.
An example using Azure is the following:

![image](https://github.com/VinciGit00/Scrapegraph-ai/assets/19621159/e8d04046-847d-478e-baa6-2929a6255b99)
