### ISSUE TITLE
Not seen the Gemini API_key when pass

### ISSUE THREAD

**Issue by Arinze1020** [VinciGit00/Scrapegraph-ai#152]
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Gemini
__root__
  Did not find google_api_key, please add an environment variable `GOOGLE_API_KEY` which contains it, or pass `google_api_key` as a named parameter. (type=value_error)

**Comment by VinciGit00** [comment]
give me the example

**Comment by Arinze1020** [comment]
Yes is Embedding 
'''from scrapegraphai.graphs import SmartScraperGraph
import os
from dotenv import load_dotenv, dotenv_values
load_dotenv()
GOOGLE_APIKEY = os.getenv('GOOGLE_API_KEY')


# Define the configuration for the graph
graph_config = {
    "llm": {
        "api_key": GOOGLE_APIKEY,
        "model": "gemini-pro",
    },
}

# Create the SmartScraperGraph instance
smart_scraper_graph = SmartScraperGraph(
    prompt="List me all the articles",
    source="https://perinim.github.io/projects",
    config=graph_config
)

result = smart_scraper_graph.run()
print(result)
'''

getting this Error 
''' raise ValueError("Embedding Model missing or not supported")
ValueError: Embedding Model missing or not supported'''

**Comment by VinciGit00** [comment]
ok I just add embeddings for google gemini, the next release will include it.
As soon we deploy the new version we willl let you know

**Comment by Arinze1020** [comment]
Alright thanks

**Comment by PeriniM** [comment]
@Arinze1020 added the google embeddings support in this PR 36a1522, you just need to specify the embedder model in the graph_config

**Comment by Arinze1020** [comment]
Can you share a snippet on how to add it to graph?

**Comment by VinciGit00** [comment]
pls install this version and let us know with the same script before
<img width="345" alt="Screenshot 2024-05-05 alle 20 33 53" src="https://github.com/VinciGit00/Scrapegraph-ai/assets/88108002/67d09501-3d29-4611-98f6-86a2ff0ef319">

**Comment by shkamboj1** [comment]
try now @Arinze1020

**Comment by Arinze1020** [comment]
Which version should I update to try it?

**Comment by PeriniM** [comment]
@Arinze1020 hei install the 0.9.0b7

**Comment by shkamboj1** [comment]
Try changing some other source. May be results not coming on this case

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
