### ISSUE TITLE
Case XX: Extracting information using aws Bedrock

### ISSUE THREAD

**Issue by madeepakkumar1** [VinciGit00/Scrapegraph-ai#156]
**Is your feature request related to a problem? Please describe.**
I am a aws bedrock user and interested in integrating ScrapeGraph with aws Bedrock models ecosystem.

**Describe the solution you'd like**
Would like to add aws bedrock models easy integration which will open door for bedrock models users also.

**Describe alternatives you've considered**
As a alternatives, already good LLM modes got the integration like openai, groq, mistral, docker, gemini etc.

**Additional context**
NA

**Comment by VinciGit00** [comment]
It has bedrock

**Comment by madeepakkumar1** [comment]
Helpful, If you could share example for same!

**Comment by f-aguzzi** [comment]
Check out [this gist](https://gist.github.com/JGalego/67a3db0005f5ed052224e549e8ee627c). As soon as #228 gets merged, Bedrock will be fully supported.
