### ISSUE TITLE
PDFScraperGraph does not work

### ISSUE THREAD

**Issue by milad1378yz** [VinciGit00/Scrapegraph-ai#172]
based on this code:
from scrapegraphai.graphs.pdf_scraper_graph import PDFScraperGraph
from scrapegraphai.utils import prettify_exec_info

OPENAI_API_KEY = "sk-"
graph_config = {"llm": {"api_key": OPENAI_API_KEY, "model": "gpt-3.5-turbo"}}

smart_scraper_graph = PDFScraperGraph(
    "List me scope 1 emissions in the document.",
    "test.pdf",
    graph_config
)

result = smart_scraper_graph.run()
print(result)

I am getting the following error:
File "C:\Users\milad\OneDrive - UBC\Desktop\works\venv\lib\site-packages\scrapegraphai\nodes\fetch_node.py", line 58, in execute
    input_keys = self.get_input_keys(state)
  File "C:\Users\milad\OneDrive - UBC\Desktop\works\venv\lib\site-packages\scrapegraphai\nodes\base_node.py", line 90, in get_input_keys
    raise ValueError(
ValueError: Error parsing input keys for Fetch: No state keys matched the expression.

**Comment by VinciGit00** [comment]
you should open by yourself the "test.pdf" file

**Comment by VinciGit00** [comment]
hi, we fixed it, in the next days it will go to the main
