### ISSUE TITLE
Google Colab example does not work

### ISSUE THREAD

**Issue by peterhgruber** [VinciGit00/Scrapegraph-ai#173]
Running the Google Colab example produces an error.

**To Reproduce**
1. Select "Open in Colab"
2. Enter OpenAI credentials
3. Run top to bottom
4. Obtain error (screenshot below)

**Expected behavior**
No error

**Screenshots**
<img width="1133" alt="Screenshot 2024-05-08 at 00 22 13" src="https://github.com/VinciGit00/Scrapegraph-ai/assets/42358482/c3e4c601-9832-4049-818a-7acaf542bc08">

**Desktop (please complete the following information):**
Not really relevant, but ... 
- OS: OSX 13.6.3
 - Safari 16.6

**Comment by aminrabinia** [comment]
comment out the embeddings:
```
graph_config = {
    "llm": {
        "api_key": OPENAI_API_KEY,
        "model": "gpt-3.5-turbo",
        "temperature":0,
    },
    # "embeddings":{
    # }
}
```

**Comment by PeriniM** [comment]
Thank you guys, I fixed the example :)
