### ISSUE TITLE
GoogleGenerativeAIEmbeddings is not defined

### ISSUE THREAD

**Issue by aliavni** [VinciGit00/Scrapegraph-ai#182]
**Describe the bug**
Hi, I am running the **Case 6: Extracting information using Gemini** example in the readme. But, I am getting the following error:

```
NameError: name 'GoogleGenerativeAIEmbeddings' is not defined
```

**To Reproduce**
1. Create a virtual env with Python 3.11.9
2. `pip install scrapegraphai==0.10.0`
3. Run the code in readme: `Case 6: Extracting information using Gemini` 

**Expected behavior**
I would expect the sample code to run successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by VinciGit00** [comment]
Please try the new beta
