### ISSUE TITLE
Implement Graph Visualization with Graphviz

### ISSUE THREAD

**Issue by PeriniM** [VinciGit00/Scrapegraph-ai#19]
### Description:
To enhance our understanding and debugging capabilities of the scraping workflows, we aim to introduce a feature for visualizing the graph structures using Graphviz. This visualization will help in quickly identifying the flow, relationships between nodes, and potential bottlenecks in the graph.

### Tasks:

- Research Graphviz syntax and integration options with Python;
- Develop a utility function or class method that converts our current graph structure into a Graphviz-compatible format;
- Ensure the visualization includes node names, types, and directional edges.

**Comment by lurenss** [comment]
Implemented
