### ISSUE TITLE
Support customizable openai endpoint

### ISSUE THREAD

**Issue by NeverOccurs** [VinciGit00/Scrapegraph-ai#196]
Tried litellm for hours but didn't work. Not so familiar with langchain. It would be better if some more examples (together_ai, openrouters) are provided. Customizable openai endpoint would be a big plus.
![image](https://github.com/VinciGit00/Scrapegraph-ai/assets/96693590/9e965097-8c50-4204-9527-9023c266e012)

**Comment by VinciGit00** [comment]
please send us the script you are using

**Comment by VinciGit00** [comment]
try this 
`graph_config = {
    "llm": {
        "model": "gpt-3.5-turbo",
        "api_key": "YOUR_API_KEY",
        "temperature": 0,
        "openai_api_base": "https://your_custom_url.com",
    },
}`
