### ISSUE TITLE
LM Studio support

### ISSUE THREAD

**Issue by Sandbird** [VinciGit00/Scrapegraph-ai#204]
**Is your feature request related to a problem? Please describe.**
Instead of using ollama (cpu only), be able to use LM Studio instead (supports GPU).

**Describe the solution you'd like**
For example, run the hermes-2 model in LM studio playground then do something like this:

```
graph_config = {
    "llm": {
        "model": "TheBloke/nous-hermes-2-mistral-7b-dpo",
        "temperature": 0,
        "format": "json",
        "base_url": "http://localhost:1234/v1",  #Point to the local server
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "temperature": 0,
        # "base_url": "http://localhost:11434",  # set ollama URL arbitrarily
    },
    "verbose": True,
}
....
```

**Comment by DiTo97** [comment]
@Sandbird seems similar to #202, and the same approach should work with LMS.

BTW, why are you saying ollama runs on CPU only? I have been running it with acceleration on any platform, barring XPUs

**Comment by carl-shen** [comment]
In my quick testing, I could get this to work, but the embedding still uses that of OpenAI's.
`graph_config = {
    "llm": {
        "api_key": "your api key",
        "model": "gpt-4",
        "temperature": 0,
        "openai_api_base": "http://localhost:1234/v1",
    },
}`


but if I install ollama and pull the embedding model, then use this config, it would use my LM Studio server for inference and my Ollama server for embedding, it seems.
`
graph_config = {
    "llm": {
        "api_key": "placeholder",
        "model": "gpt-4",
        "temperature": 0,
        "openai_api_base": "http://localhost:1234/v1",
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "base_url": "http://localhost:11434",
    }
}
`

**Comment by Sandbird** [comment]
Oh nice, thanks!, i managed to get it working as well using this:
```
# Note: You can actually leave as-is
OPENAI_API_KEY = "YOUR_API_KEY" #leave this fake one

graph_config = {
    "llm": {
        "api_key": OPENAI_API_KEY,
        "model": "gpt-4",
        "temperature": 0,
        "base_url": "http://localhost:1234/v1",
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "base_url": "http://localhost:11434",
    }
}
```

I don't know why ollama ingores my GPU, only gpt4all and LM Studio works fine.
Thank you!
