### ISSUE TITLE
Provide docker container for local Ollama (or simmilar) 

### ISSUE THREAD

**Issue by idevopstest** [VinciGit00/Scrapegraph-ai#212]
Hi , 
can you provide working docker containers for various examples 
eg. docker container for Ollama Graph from text

Thank you ;)

**Comment by VinciGit00** [comment]
Look at this link https://github.com/VinciGit00/Scrapegraph-ai/blob/main/examples/local_models/smart_scraper_ollama.py. It is also valid for docker, you have just to specify the base url
