### ISSUE TITLE
Gradio GUI support 

### ISSUE THREAD

**Issue by fuckemooncoin** [VinciGit00/Scrapegraph-ai#219]
Current streamlit.io demo is not that flexible. Would like to ask open source local install package for Gradio supported package 
1. which can be installed and exeucted on different OS. 
2. Needs to have multiple prompt input of sophisticated scrapping
3. Easy to use UI.

**Comment by VinciGit00** [comment]
Hi, please if you are interested in that you are free to modify it, it's open source
