### ISSUE TITLE
feat: add deepseek-chat 

### ISSUE THREAD

**Issue by zx9597446** [VinciGit00/Scrapegraph-ai#222]
please add deepseek-chat from deepseek.com

expose openai_base_url should work.

model name: deepseek-chat

they provide 5M token for free. thanks.

**Comment by f-aguzzi** [comment]
I'm working on this with @VinciGit00 's supervision. We'll figure this out soon.

**Comment by VinciGit00** [comment]
hi, it's in the pre/beta branch. install from there

**Comment by VinciGit00** [comment]
check it out please https://github.com/VinciGit00/Scrapegraph-ai/blob/pre/beta/examples/deepseek/smart_scarper_deepseek.py

**Comment by zx9597446** [comment]
there are 2 issues here:
1.  abstract_graph.py needs to import DeepSeek:
from scrapegraphai.models.deepseek import DeepSeek

2. Deepseek no embedding provided,  so examples needs local embedding instead.
