### ISSUE TITLE
How to custom base_url for OpenAI request?

### ISSUE THREAD

**Issue by thangnqs** [VinciGit00/Scrapegraph-ai#225]
Hi, I use proxy custom URL request using base OpenAI, but ```baseURL``` not working
This is my code:
```
graph_config = {
    "llm": {
        "api_key": "YOUR_API_KEY",
        "model": "gpt-3.5-turbo",
        "temperature": 0,
        "configuration": {
          "baseURL": "https://your_custom_url.com",
        },
    },
}
```

Any solution for this problem?

**Comment by f-aguzzi** [comment]
Try this:

```python
graph_config = {
    "llm": {
        "model": "gpt-3.5-turbo",
        "api_key": "YOUR_API_KEY",
        "temperature": 0,
        "openai_api_base": "https://your_custom_url.com",
    },
}
```

The recent `DeepSeek` implementation we added in the latest beta is something like this - it's still based on the `ChatOpenAI` class from `LangChain` but it uses a custom base URL. The code snippet above is readapted from [this example](https://github.com/VinciGit00/Scrapegraph-ai/blob/pre/beta/examples/deepseek/smart_scarper_deepseek.py). We haven't been able to test it properly but it should work.

**Comment by thangnqs** [comment]
@f-aguzzi Thanks information. How to install branch ```pre/beta``` to test on local?

**Comment by VinciGit00** [comment]
Try the new version, it should have it

**Comment by leiyu2023** [comment]
I customized the base_url, but it still gives me an error.
code:
```
graph_config = {
    "llm": {
        "model": "gpt-3.5-turbo",
        "api_key": "sk-YjB3g***************************************A3B0",
        "temperature": 0,
        "openai_api_base": "https://free.gpt.ge",
    },
}
```

error:
AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-YjB3g***************************************A3B0. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}

**Comment by VinciGit00** [comment]
yes but you  API key is not valid, pls create a new one

**Comment by thangnqs** [comment]
> I customized the base_url, but it still gives me an error. code:
> 
> ```
> graph_config = {
>     "llm": {
>         "model": "gpt-3.5-turbo",
>         "api_key": "sk-YjB3g***************************************A3B0",
>         "temperature": 0,
>         "openai_api_base": "https://free.gpt.ge",
>     },
> }
> ```
> 
> error: AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-YjB3g***************************************A3B0. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}

Yes, same issues. Though I set ```openai_api_base``` to another domain to authencation, but it still redirects authencationto openai. That's wrong!

I don't why that. I think need a new feature for custom model on base OpenAI in the next time.

**Comment by PeriniM** [comment]
@thangnqs yes the openai class verify first if the apikey is correct in the openai endpoints and then take the model from your url, the problem is if it requires authenticatoin too. 
You can look into creating a standard LLM interface compatible with Langchain [Reddit](https://www.reddit.com/r/LangChain/comments/17v1rhv/integrating_llm_rest_api_into_a_langchain/) - [CustomLLM](https://python.langchain.com/v0.1/docs/modules/model_io/llms/custom_llm/).
If you manage to do a generic CustomLLM class, plis send the PR under the models module. Thanks!

**Comment by lzl-hello** [comment]
Pls is this issue solved now? How do I call the brokering API?
