### ISSUE TITLE
Please add examples to the documentation, struggling with understanding how it works

### ISSUE THREAD

**Issue by Emasoft** [VinciGit00/Scrapegraph-ai#23]
Wonderful! I was looking for something like this library!

But I found difficult to use the library because there are no examples.

For instance, I need to extract the **name**, the _province_ and the **address** of all cinema theaters listed on this website:  

PROVINCES
https://www.mymovies.it/cinema/
  
The information is divided on 3 levels: the above page contains the list of provinces, each cuty province links to the names of the theaters:

PROVINCES->THEATERS 
https://www.mymovies.it/cinema/roma/

And each theatre name links to the address:

PROVINCES->THEATRES->ADDRESS
https://www.mymovies.it/cinema/roma/5157/

Sometimes there is a 4th level for smaller towns inside the province area of the city:

PROVINCES->SMALL_TOWNS
https://www.mymovies.it/cinema/roma/fianoromano/

PROVINCES->SMALL_TOWNS->THEATRES->ADDRESS
https://www.mymovies.it/cinema/roma/fianoromano/5102/

How am I supposed to ask that and get back the list of all Italian cinema theatres names and address divided by province?

Thanks in advance!

**Comment by VinciGit00** [comment]
Hi, thank you for the trust, we will do it as soon as possible

**Comment by lurenss** [comment]
Hi @Emasoft, currently scrapegraph can scrape "small" websites, however we are working to extend to more complex websites, stay tuned for updates

**Comment by VinciGit00** [comment]
Hi Emasoft we added examples in the section [https://github.com/VinciGit00/Scrapegraph-ai/tree/main/examples/graph_examples](examples) of the library.
You can find more documentation in `[https://scrapegraph-doc.onrender.com/docs/intro](url) or [https://scrapegraph-ai.readthedocs.io/en/latest/](url).
If you need more help you can find us in the contacts of the README.md
