### ISSUE TITLE
gpt-4o Model support

### ISSUE THREAD

**Issue by Mindgames** [VinciGit00/Scrapegraph-ai#232]
We need the gpt-4o model support

**Comment by lurenss** [comment]
Stay tuned man

**Comment by Mindgames** [comment]
> Stay tuned man

Thanks it cuts execution time with 50%. 

**FYI running the beta I get**
`compressed_document = [Document(page_content=cleanup_html(data, source),
UnboundLocalError: local variable 'data' referenced before assignment` 

-- My work around for now is to manually update the models in the stable version code
