### ISSUE TITLE
Error when trying to use azure openai

### ISSUE THREAD

**Issue by OrhanYaz** [VinciGit00/Scrapegraph-ai#236]
**Describe the bug**
When I tried to repreduce the azure openai example using my credentials I faced a bug at the search graph step.

**To Reproduce**
1. create the .env file and fill it with the api keys and necessary informations to use mode from azure openai
2. then keep runing the code until the search graph
3. see the following error

**Screenshots**
![image](https://github.com/VinciGit00/Scrapegraph-ai/assets/23522754/a2ea3c73-ba16-42f3-b8ee-51e29998b093)
![image](https://github.com/VinciGit00/Scrapegraph-ai/assets/23522754/6ab75b4a-a505-47a1-966e-90f55881909a)

**Comment by PeriniM** [comment]
Hey it's fixed in 096b665 by replacing the deep copy with a shallow one. try installing the 1.0.1
