### ISSUE TITLE
Is there a way extract images or image links from the source using prompt?

### ISSUE THREAD

**Issue by anirudh1800** [VinciGit00/Scrapegraph-ai#240]
**Is your feature request related to a problem? Please describe.**
I want to extract images from a website matching a prompt

**Describe the solution you'd like**
Use same SmartScraperGraph API but return image links or special scraper API designed for image results

**Describe alternatives you've considered**
Tried different prompts but didn't get any sensible outputs. 

**Additional context**

**Comment by PeriniM** [comment]
Hey @anirudh1800, you are asking at the right time! We just released OmniScraperGraph which uses GPT-4o and GPT-4 to extract information and describe the content of images as well! #238

**Comment by anirudh1800** [comment]
Great!! Excited to try to this now. Thank you.
