### ISSUE TITLE
Run Ollama/Local Models on the Google Colab

### ISSUE THREAD

**Issue by Nick088Official** [VinciGit00/Scrapegraph-ai#275]
**Is your feature request related to a problem? Please describe.**
As openai & google api key cost money, it would be better if there's a way to run models directly on google colab

**Describe the solution you'd like**
I'd like to be able to use the google colab without having to use an api key, any local models like in the examples of this github repository would be good

**Comment by VinciGit00** [comment]
thank you we will do a tutorial

**Comment by Nick088Official** [comment]
Thank you, hope it comes out soon

**Comment by VinciGit00** [comment]
Hi, please follow the following tutorial:
[https://github.com/ScrapeGraphAI/ScrapeGraphAI-collab-ollama](https://github.com/ScrapeGraphAI/ScrapeGraphAI-collab-ollama)
