### ISSUE TITLE
Subprocess-exited-with-error 

### ISSUE THREAD

**Issue by jondoescoding** [VinciGit00/Scrapegraph-ai#285]
**Describe the bug**
When I attempt to pip install the package I get the following error.

          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**To Reproduce**
- Type pip install scrapegraph-ai
- See error

**Expected behavior**
I excpeted the python package to be installed

**Desktop (please complete the following information):**
 - OS: Windows (WSL)

**Comment by PeriniM** [comment]
Hey @jondoescoding check the WSL [Installation](https://scrapegraph-ai.readthedocs.io/en/latest/getting_started/installation.html) and let me know!

**Comment by VinciGit00** [comment]
whcich python version are you using?

**Comment by jondoescoding** [comment]
> whcich python version are you using?

3.11.5

**Comment by brakenick** [comment]
I got the same issue on macOS 14.4.1 with python 3.12.3 when running pip3 install scrapegraphai.

`AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?`

**Comment by pn1-ms** [comment]
Get the same issue on macOS, python 3.21.3 on install. Looks like it's the Yahoo search support that is causing this:

    Collecting yahoo-search-py==0.3 (from scrapegraphai)
    Using cached yahoo-search-py-0.3.tar.gz (11 kB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... error
    error: subprocess-exited-with-error

I get the same issue when trying to install the yahoo-search-py package using pip.

**Comment by PeriniM** [comment]
Hey guys we fixed the error in the new release #302 and python 3.12 is now supported! Thanks
