### ISSUE TITLE
GPT-4o on Azure giving 'Model not supported' Error

### ISSUE THREAD

**Issue by supernitin** [VinciGit00/Scrapegraph-ai#286]
I'm trying to use GPT-4o on Azure as my LLM

`llm = AzureChatOpenAI(
    #azure_endpoint=os.environ.get("AZURE_OPENAI_ENDPOINT"),
    #api_key=os.environ.get("AZURE_OPENAI_API_KEY"),
    api_version="2024-02-01",
    #azure_deployment=os.environ.get("AZURE_OPENAI_DEPLOYMENT"),
    model="gpt-4o",
    model_version="2024-05-13",
    max_tokens=4000,
)`

However, I get 'model not supported' when attempting to do so:

`KeyError: 'Model not supported'`

**Comment by VinciGit00** [comment]
thank you, we will fix it

**Comment by VinciGit00** [comment]
Please can you fix it?

**Comment by VinciGit00** [comment]
hi, now we added it
