### ISSUE TITLE
Chapta error 

### ISSUE THREAD

**Issue by alby696** [VinciGit00/Scrapegraph-ai#296]
Trying to scrape the Mediaworld site I get the error that no information is found.
Result 
{'answer': 'It is not possible to get the list of all products, description and price from the discarded content because there is no product information within the content. The content contains error messages and user instructions, but does not provide any product information."}

Running the test with another scraper via laravel, I can see that the site returns this wording:
Dear visitor,
Unfortunately, this happened too fast for us. To continue and to see all offers from Mediamarkt, please complete the captcha below.
Please turn JavaScript on and reload the page.Please enable Cookies and reload the page.

Thanks

Code

`from scrapegraphai.graphs import SmartScraperGraph
import nest_asyncio
nest_asyncio.apply()

graph_config = {
    "llm" : {
        "model" : "ollama/llama3",
        "temperature" : 0,
        "format" : "json",
        "base_url" : "http://localhost:11434",
    },
    "embeddings" : {
        "model" : "ollama/nomic-embed-text",
        "base_url" : "http://localhost:11434",
    },
    "verbose" : True,
}

smart_scraper_graph = SmartScraperGraph (
    prompt = "List me the product with their price",
    source = "https://www.mediaworld.it/it/brand/apple/iphone/iphone-15-pro",
    config = graph_config
)

result = smart_scraper_graph.run()

print(result)`

**Comment by DiTo97** [comment]
@alby696 we don't have a CAPTCHA solver or support for dynamic content (see #279) yet

**Comment by PeriniM** [comment]
Hey @alby696 try setting `"headless": False` in the graph_config and it should work!
