### ISSUE TITLE
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 32.0 seconds as it raised ResourceExhausted: 429 Resource has been exhausted (e.g. check quota)..

### ISSUE THREAD

**Issue by Kingki19** [VinciGit00/Scrapegraph-ai#300]
I know this is not really a bug, but rather i have reach quota limit. My question is why there's only me who has this error? I have try to find the problem online using Google but did not find same problem. 

I am sorry, i have asked many questions for you.

**Comment by VinciGit00** [comment]
try to increase the rate limit on the gemini platform
