### ISSUE TITLE
ValueError: No HTML body content found, please try setting the 'headless' flag to False in the graph configuration. (Urgent help wanted)

### ISSUE THREAD

**Issue by MalakW** [VinciGit00/Scrapegraph-ai#308]
Initially, it worked and provided output, but it has stopped working. I have been trying to resolve this error for three days. Despite using a VPN and adding money to OpenAI, the error persists.

<img width="678" alt="Screenshot 2024-05-27 122100" src="https://github.com/VinciGit00/Scrapegraph-ai/assets/51320105/e7f30f07-c666-4b78-a92a-b3d1b13cb5fe">

**Comment by PeriniM** [comment]
Hey @MalakW, the headless flag should not be inside the "browser" key in the graph configuration. Let me know

**Comment by MalakW** [comment]
> the headless flag should not be inside the "browser" key in the graph configuration.

like this you mean?

<img width="821" alt="image" src="https://github.com/VinciGit00/Scrapegraph-ai/assets/51320105/5e298511-eee5-497b-8df2-fae365e722d5">

**Comment by MalakW** [comment]
hello, any help regarding this issue?

**Comment by wangdongpeng1** [comment]
look this ^_^ hope help for you

```
graph_config = {
    "llm": {
        "api_key": "<Your API KEY>",
        "model": "oneapi/qwen-turbo",
        "base_url": "http://127.0.0.1:13000/v1", 
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "base_url": "http://127.0.0.1:11434",
    },
    "headless": False
}
```

**Comment by VinciGit00** [comment]
hi @MalakW the reason is because you have not installed playwright, look this collar to see how Is implemented [link](https://colab.research.google.com/drive/1sEZBonBMGP44CtO6GQTwAlL0BGJXjtfd?usp=sharing)

**Comment by Pankti99** [comment]
Hey **@MalakW** You can try this.

```
import asyncio
import sys
from playwright.async_api import async_playwright

graph_config = {
    "llm": {
        "model_instance": llm_model_instance
    },
    "embeddings": {
        "model_instance": embedder_model_instance
    },
    "browser": {
        "headless": False
    }
}
def scrape_website(prompt, source):
    print(prompt, source)
    # Ensure the event loop policy is set correctly for Windows
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())

    # Create the SmartScraperGraph instance
    smart_scraper_graph = SmartScraperGraph(
        prompt=prompt,
        source=source,
        config=graph_config
    )

    result = smart_scraper_graph.run()
```
