### ISSUE TITLE
Ability to use locally hosted AI Model

### ISSUE THREAD

**Issue by Willxiam** [VinciGit00/Scrapegraph-ai#32]
**Is your feature request related to a problem? Please describe.**
Using OpenAI's presents known privacy problems. 

**Describe the solution you'd like**
The ability local models like 
[TinyLlama 1.1B v1.0](https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF) 
[OpenChat 3.5 0106](https://huggingface.co/TheBloke/openchat-3.5-0106-GGUF)

**Describe alternatives you've considered**
I am on the lookout

**Comment by VinciGit00** [comment]
Hi, Willxiam, this is a long term goal, if you want to help our contribute us feel free to contact. You can find the contacts on the readme of the repo

**Comment by VinciGit00** [comment]
Hi Willxiam, we just add the possibility to run local models with Ollama, if u need more informations feel free to contact us write me at mvincig11@gmail.com
