### ISSUE TITLE
Can't install in Linux or WSL.

### ISSUE THREAD

**Issue by pdavis68** [VinciGit00/Scrapegraph-ai#326]
**Describe the bug**
I'm simply running `pip install scrapegraphai`

When I run it in Windows, it installs fine.
But if I try to run it in WSL2, I get:
ERROR: Could not find a version that satisfies the requirement scrapegraphai (from versions: none)
ERROR: No matching distribution found for scrapegraphai

I created a docker container with ubuntu and python 3.12 and logged into it and ran it `pip install scrapegraphai` and I got the same error I got in WSL2.

Does it only work in Windows?

**To Reproduce**
1. `pip install scrapegraphai` on WSL2 or Linux machines

**Expected behavior**
I expect it to install without an error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows, WSL2, and Ubuntu 20.04 LTS

**Comment by wesleymenezes** [comment]
Same error for me:
OS: Oracle Linux Server 8.10

1. `pip install scrapegraphai`

result is:
ERROR: Could not find a version that satisfies the requirement scrapegraphai (from versions: none)
ERROR: No matching distribution found for scrapegraphai
