### ISSUE TITLE
TypeError AsyncChromiumLoader.__init__() got an unexpected keyword argument 'headless'

### ISSUE THREAD

**Issue by CasKirch** [VinciGit00/Scrapegraph-ai#334]
**Describe the bug**
I get a TypeError when trying to run the script examples indicating that AsyncChromiumLoader.__init__() got an unexpected keyword argument 'headless'

**To Reproduce**

from scrapegraphai.graphs import SmartScraperGraph
OPENAI_API_KEY = "YOUR_API_KEY"

graph_config = {
    "llm": {
        "api_key": OPENAI_API_KEY,
        "model": "gpt-3.5-turbo",
    },
}

smart_scraper_graph = SmartScraperGraph(
    prompt="List me all the articles",
    # also accepts a string with the already downloaded HTML code
    source="https://perinim.github.io/projects",
    config=graph_config
)

result = smart_scraper_graph.run()
print(result)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome (using Jupyter Notebook)

**Additional context**
I have very little programming skills

**Comment by VinciGit00** [comment]
try with this config:
```python
graph_config = {
"llm": {
"api_key": OPENAI_API_KEY,
"model": "gpt-3.5-turbo",
},
"headless": "false",

}
```

**Comment by VinciGit00** [comment]
and if you are using a Jupyter notebook take reference from here:
[https://colab.research.google.com/drive/1sEZBonBMGP44CtO6GQTwAlL0BGJXjtfd?usp=sharing](url)
