### ISSUE TITLE
openai.AuthenticationError: Error code: 401

### ISSUE THREAD

**Issue by yuhua01** [VinciGit00/Scrapegraph-ai#337]
hello, Why does the use of deepseek key cause the problem of 401? Can you help to solve it
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-f56bc***********************5568. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by VinciGit00** [comment]
ok, please provide the code

**Comment by yuhua01** [comment]
> 好的，请提供代码好的，请提供代码


您好，这是我的代码
""" 
Basic example of scraping pipeline using SmartScraper
"""

import os
from dotenv import load_dotenv
from scrapegraphai.graphs import SmartScraperGraph
from scrapegraphai.utils import prettify_exec_info

load_dotenv()

# ************************************************
# Define the output schema for the graph
# ************************************************

schema= """
    { 
    "Projects": [
        "Project #": 
            { 
                "title": "...", 
                "description": "...", 
            }, 
        "Project #": 
            { 
                "title": "...", 
                "description": "...", 
            } 
        ] 
    } 
"""

# ************************************************
# Define the configuration for the graph
# ************************************************

deepseek_key = "sk-f56bc***********************5568"

graph_config = {
    "llm": {
        "model": "deepseek-chat",
        "openai_api_key": deepseek_key,
        "openai_api_base": 'https://api.deepseek.com/v1',
    },
    "verbose": True,
}

# ************************************************
# Create the SmartScraperGraph instance and run it
# ************************************************

smart_scraper_graph = SmartScraperGraph(
    prompt="List me all the projects with their description.",
    # also accepts a string with the already downloaded HTML code
    source="https://perinim.github.io/projects/",
    schema=schema,
    config=graph_config
)
print(smart_scraper_graph)
result = smart_scraper_graph.run()
print(result)

# ************************************************
# Get graph execution info
# ************************************************

graph_exec_info = smart_scraper_graph.get_execution_info()
print(prettify_exec_info(graph_exec_info))

**Comment by yuhua01** [comment]
> 好的，请提供代码好的，请提供代码
您好 这是我的代码
""" 
Basic example of scraping pipeline using SmartScraper
"""

import os
from dotenv import load_dotenv
from scrapegraphai.graphs import SmartScraperGraph
from scrapegraphai.utils import prettify_exec_info

load_dotenv()

# ************************************************
# Define the output schema for the graph
# ************************************************

schema= """
    { 
    "Projects": [
        "Project #": 
            { 
                "title": "...", 
                "description": "...", 
            }, 
        "Project #": 
            { 
                "title": "...", 
                "description": "...", 
            } 
        ] 
    } 
"""

# ************************************************
# Define the configuration for the graph
# ************************************************

deepseek_key = "sk-f56bc***********************5568"

graph_config = {
    "llm": {
        "model": "deepseek-chat",
        "openai_api_key": deepseek_key,
        "openai_api_base": 'https://api.deepseek.com/v1',
    },
    "verbose": True,
}

# ************************************************
# Create the SmartScraperGraph instance and run it
# ************************************************

smart_scraper_graph = SmartScraperGraph(
    prompt="List me all the projects with their description.",
    # also accepts a string with the already downloaded HTML code
    source="https://perinim.github.io/projects/",
    schema=schema,
    config=graph_config
)
print(smart_scraper_graph)
result = smart_scraper_graph.run()
print(result)

# ************************************************
# Get graph execution info
# ************************************************

graph_exec_info = smart_scraper_graph.get_execution_info()
print(prettify_exec_info(graph_exec_info))

**Comment by VinciGit00** [comment]
is deepseek enabled where you live?

**Comment by yuhua01** [comment]
Yes, I can use deepseek where I live, and it's ok for me to test it with other programs

**Comment by VinciGit00** [comment]
please can you send me in private a deepseek key?

**Comment by yuhua01** [comment]
Ok, I have sent it to you in the email.

**Comment by yuhua01** [comment]
sk-f56bc98f3fca4387aa05465c6d1f5568

发自我的iPhone


------------------ Original ------------------
From: Marco Vinciguerra ***@***.***&gt;
Date: Tue,Jun 4,2024 9:35 PM
To: VinciGit00/Scrapegraph-ai ***@***.***&gt;
Cc: yuhua01 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [VinciGit00/Scrapegraph-ai] openai.AuthenticationError: Errorcode: 401 (Issue #337)





 
please can you send me in private a deepseek key?

**Comment by VinciGit00** [comment]
ok, the problem is that deepseek does not support embeddings, you should add another provider for the embeddings.
I tried the example with your apis keys and it works. Look at this example 
[https://github.com/VinciGit00/Scrapegraph-ai/blob/main/examples/deepseek/smart_scraper_deepseek.py](https://github.com/VinciGit00/Scrapegraph-ai/blob/main/examples/deepseek/smart_scraper_deepseek.py)

**Comment by yuhua01** [comment]
Hi, I tried this example but the original problem still exists, can you let me see your example and results via email

**Comment by VinciGit00** [comment]
Have you installed ollama?

**Comment by yuhua01** [comment]
ollama has not been installed, maybe it is my agent in this place.
My question can be closed temporarily. Thank you very much for your help

**Comment by VinciGit00** [comment]
you should install Ollama or using another  provider on the embeddings
