### ISSUE TITLE
Problem running the example notebook in the readme

### ISSUE THREAD

**Issue by tindo2003** [VinciGit00/Scrapegraph-ai#342]
**Describe the bug**
Ran into KeyError when running the [ScrapeGraphAI - Examples Colab Notebook ](https://colab.research.google.com/drive/1sEZBonBMGP44CtO6GQTwAlL0BGJXjtfd?usp=sharing).

![Screenshot 2024-06-04 at 9 12 11 PM](https://github.com/VinciGit00/Scrapegraph-ai/assets/62820303/69a1e359-d620-4157-bd10-5a094931ef6b)

This is the result of running the following cell:
![Screenshot 2024-06-04 at 9 15 03 PM](https://github.com/VinciGit00/Scrapegraph-ai/assets/62820303/eb31419d-450b-47f2-bb93-cc485d55697c)

This is my first time reporting an error, so if you find anything lacking, please let me know. Thank you!

**Comment by tindo2003** [comment]
Hello,
Thank you for your prompt fix! The current error is fixed, but I just got another one. I can close this one, and make a pull request since I think I know what the issue is.

**Comment by tindo2003** [comment]
Never mind, I could not fix it in the source code. In the following cell, 
![Screenshot 2024-06-05 at 10 49 01 AM](https://github.com/VinciGit00/Scrapegraph-ai/assets/62820303/268e374f-50c4-48d1-ba1c-3f42d63c745f)

Can you please change it to something like 
```
result, execution_info = graph.execute(
    {
        "user_prompt": "Describe the content",
        "url": "https://perinim.github.io/projects/",
    }
)
```
as it was done in examples/openai/custom_gr
![Screenshot 2024-06-05 at 10 50 12 AM](https://github.com/VinciGit00/Scrapegraph-ai/assets/62820303/3d9d2fcb-0731-4792-9263-937f52547d7c)

Thanks a lot!
aph_openai.py. Right now, the error

**Comment by PeriniM** [comment]
Hey @tindo2003 modified the colab, thanks!
