### ISSUE TITLE
Support for SPA's that has deferred content loading

### ISSUE THREAD

**Issue by ja-wxu** [VinciGit00/Scrapegraph-ai#367]
**Is your feature request related to a problem? Please describe.**
Single page web apps that load content post initial page load does it work right now. It returns an error suggesting the page is empty.

**Describe the solution you'd like**
Add an additional playwright config to wait or to execute some locator function. 

**Describe alternatives you've considered**
Let LLM decide whether to wait

**Additional context**

**Comment by VinciGit00** [comment]
hi, take a look on this [https://scrapegraph-doc.onrender.com/docs/Examples/slow_mo_](link)

**Comment by ja-wxu** [comment]
hi @VinciGit00,

That link doesn't work. The examples under https://scrapegraph-doc.onrender.com/docs/Examples/ don't seem to have anything that'd look like a `slow_mo_...`

**Comment by Kilowhisky** [comment]
I think they mean this: https://scrapegraph-doc.onrender.com/docs/Examples/extras/slow_mo
