### ISSUE TITLE
Do we have a output parser to get a certain format output

### ISSUE THREAD

**Issue by Vikrant-Khedkar** [VinciGit00/Scrapegraph-ai#383]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VinciGit00** [comment]
hi, the dataset is always in json, but:
- you can specify the output schema like this [https://scrapegraph-doc.onrender.com/docs/Examples/Ollama/smart_scraper_schema_ollama](https://scrapegraph-doc.onrender.com/docs/Examples/Ollama/smart_scraper_schema_ollama)
- in the utils folder there are the functions for convertuing in csv
