### ISSUE TITLE
Could it support other chinese ollama embedding models?

### ISSUE THREAD

**Issue by MedicalAGI** [VinciGit00/Scrapegraph-ai#388]
I wanto to know that whether it support other chinese ollama embedding models?  eg. when I add "shaw/dmeta-embedding-zh" in scrapegraphai/helpers/models_tokens.py and run,I got the error "ValueError: Error raised by inference API HTTP code: 500, {"error":"failed to generate embedding"}"

**Comment by VinciGit00** [comment]
ok, we will do it!

**Comment by VinciGit00** [comment]
can I have an example of use case?

**Comment by VinciGit00** [comment]
hi, please install the new beta and let me know! if you can help us to list Chinese models we would be glad! is not easy from European people to find it

**Comment by MedicalAGI** [comment]
OK,thanks! for example,"chevalblanc/acge_text_embedding" and "smartcreation/dmeta-embedding-zh" embedding model.They are all good embedding models and are available on ollama.

**Comment by VinciGit00** [comment]
Hi, I added it, please if you have more to suggest me we will add it

**Comment by MedicalAGI** [comment]
Thanks,I try it now!

**Comment by MedicalAGI** [comment]
em,but when I use "chevalblanc/acge_text_embedding" as the embedding model,I got the error "ValueError: Error raised by inference API HTTP code: 500, {"error":"failed to generate embedding"}",and the ollama version is 0.1.42

**Comment by VinciGit00** [comment]
is it opened?

**Comment by MedicalAGI** [comment]
Yes.I deploy these model in my own computer with ollama
