### ISSUE TITLE
Allow using a remote Ollama

### ISSUE THREAD

**Issue by ftoppi** [VinciGit00/Scrapegraph-ai#53]
People don't always run apps on the same computer where they run Ollama.
Since you provide a docker-compose.yml to run ollama, you might run your app in another container.

Allow people to set `base_url` to configure ChatOllama to connect to a different URL than http://localhost:11434 .

**Comment by VinciGit00** [comment]
yes, this is some futures development, we will do it and close the request, in particular for models runner on servers, huggingface, azure-ai and AWS
