### ISSUE TITLE
Ollama embedding model is always `llama2`

### ISSUE THREAD

**Issue by ftoppi** [VinciGit00/Scrapegraph-ai#54]
You don't configure `OllamaEmbeddings` in `rag_node.py`, therefore it is always defined with the default settings.

https://github.com/VinciGit00/Scrapegraph-ai/blob/8ef49a03e007428eea91c9bd4ee69e27256c1be1/scrapegraphai/nodes/rag_node.py#L94

Default settings: https://api.python.langchain.com/en/latest/embeddings/langchain_community.embeddings.ollama.OllamaEmbeddings.html#langchain_community.embeddings.ollama.OllamaEmbeddings

I guess you didn't notice because you started with `llama2`.

**Comment by PeriniM** [comment]
You are right, thank you! I fixed it in commit 8b915e3
