### ISSUE TITLE
Adding debugging mode

### ISSUE THREAD

**Issue by sorenaldridge** [VinciGit00/Scrapegraph-ai#97]
**Is your feature request related to a problem? Please describe.**
I am having a challenge finding out where my project is going wrong. When I run a prompt I receive {} as the output and don't get any further information as to why I got that as the result. 

**Describe the solution you'd like**
Some sort of debugging mode with higher level of detail around each stage of the pipeline and what succeeded and failed to get down to the root of the issue.

**Comment by VinciGit00** [comment]
Give us an example

**Comment by PeriniM** [comment]
Hei @sorenaldridge, after having executed the graph you can get the info of the final state using `smart_scraper_graph.get_state()`.
Share the output so we can check it out!
