### ISSUE TITLE
Hugging Face API

### ISSUE THREAD

**Issue by fdaudens** [VinciGit00/Scrapegraph-ai#99]
Would it be possible to add the Hugging Face API to access many different models?

**Comment by PeriniM** [comment]
Yes sure! We are gonna add it to the next release, you can check the development in the pre/beta branch and give suggestions in our Discord :)

**Comment by shkamboj1** [comment]
Once the above gets merged: you can use hugging face models using this snippet at examples/huggingfacehub/smart_scraper_huggingfacehub.py

**Comment by VinciGit00** [comment]
hi, can u try it pls?

**Comment by fdaudens** [comment]
Thanks a lot, it works like a charm! I've built a Gradio interface to showcase it: https://huggingface.co/spaces/JournalistsonHF/ai-scraper

**Comment by PeriniM** [comment]
@fdaudens really cool! Will share it on social media ;)
